---
title: "Verifying sample relationships using genotypes or inferred genotypes"
shorttitle: "Verifying sample relationships"
package: "omicsPrint"
author: 
- name: "Maarten van Iterson"
  affiliation: 
  - "Department of Medical Statistics and Bioinformatics, Section Moleculair Epidemiology, Leiden University Medical Center"
  email: mviterson@gmail.com
- name: "Davy Cats"
  affiliation: 
  - "Department of Medical Statistics and Bioinformatics, Section Moleculair Epidemiology, Leiden University Medical Center"
  email: davycats.dc@gmail.com
date: "`r Sys.Date()`"
abstract: >
  Analysis of multiple omics datatypes from the same individuals is
  becoming increasingly common. For example, several data repositories
  contain genetic, transcriptomic and epigenetic (DNA methylation)
  measurements on the same individuals, e.g. TCGA, Geuvadis,
  BBMRI/BIOS, etc. We have developed a tool that can verify the sample
  relationships between and across omics types. A small number of
  misspecified samples can destroy analyses for example assuming an
  analysis on unrelated individuals whereas parent offspring relations
  exist.
output: 
  BiocStyle::html_document2:
    toc: true
    toc_float:
      collapsed: false
vignette: >
  %\VignetteIndexEntry{Verifying sample relationships using genotypes or inferred genotypes}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
bibliography: omicsPrint.bib
---

```{r setup, include=FALSE}	
suppressPackageStartupMessages({
    library(BiocStyle)
    library(omicsPrint)
    library(GEOquery)
    library(SummarizedExperiment)
})
```
	

```{r, downloaddata}	
library(GEOquery)
library(SummarizedExperiment)
##gset <- getGEO("GSE73412", GSEMatrix=TRUE, AnnotGPL=FALSE)
##this is more stable somehow?
file <- tempfile()
download.file("ftp://ftp.ncbi.nlm.nih.gov/geo/series/GSE73nnn/GSE73412/matrix/GSE73412_series_matrix.txt.gz", file)
gset <- getGEO(filename=file)

se <- makeSummarizedExperimentFromExpressionSet(gset)
se
```
	
```{r, extractrelations}	
library(omicsPrint)
r <- expand.grid(idx=colnames(se), idy=colnames(se))
r$Xfam <- substr(as.character(colData(se)[r$idx, "characteristics_ch1.3"]),
                 21, 29)
r$Yfam <- substr(as.character(colData(se)[r$idy, "characteristics_ch1.3"]),
                 21, 29)
r$Xrole <- substr(as.character(colData(se)[r$idx, "characteristics_ch1.3"]),
                  31, 50)
r$Yrole <- substr(as.character(colData(se)[r$idy, "characteristics_ch1.3"]),
                  31, 50)
r[r == " N/A"] <- ""

r$relationship <- "unrelated"

fun <- function(x) {
    if (x["idx"] == x["idy"]){
        return("identical")
    }

    if (x["Xfam"] == "" || x["Yfam"] == ""){
        return("unrelated")
    }
    ##print(x)
    if (x["Yfam"] == x["Xfam"]){
        roles <- x[c("Xrole", "Yrole")]
        ##print(roles)
        if ("(son)" %in% roles && "(father)" %in% roles){
            return("father/son")
        } else if ("(son)" %in% roles && "(grandfather)" %in% roles) {
            return("grandfather/grandson")
        } else if ("(son)" %in% roles && "(uncle)" %in% roles){
            return("uncle/nephew")
        } else if ("(father)" %in% roles && "(grandfather)" %in% roles) {
            return("father/son")
        } else if ("(father)" %in% roles && "(uncle)" %in% roles) {
            return("brother")
        } else if ("(grandfather)" %in% roles && "(uncle)" %in% roles) {
            return("father/son")
        } else if (sum(roles == "(uncle)") == 2 || sum(roles == "(son)") == 2) {
            return("brother")
        }
    } else {
        return("unrelated")
    }
}

r$relationship <- apply(r, 1, fun)
head(r)
```

```{r, omicsprint}	
data(hm450.manifest.pop.GoNL)
cpgs <- names(hm450.manifest.pop.GoNL[
    mcols(hm450.manifest.pop.GoNL)$MASK.snp5.EAS])

se2 <- se[cpgs,]

se3 <- se[, se$characteristics_ch1.3 != "family relationship: N/A"]
se4 <- se3[cpgs,]

gt <- beta2genotype(se4, assayName = "exprs")
data <- alleleSharing(gt, relations = r, rel.col = "relationship", verbose = TRUE)
mismatches <- inferRelations(data)
mismatches
```

# SessionInfo #

```{r, sessioninfo}
sessionInfo()
```


