---
title: "omicsPrint: detection of data linkage errors in multiple omics studies"
shorttitle: "Verifying sample relationships"
package: "omicsPrint"
author: 
- name: "Maarten van Iterson"
  affiliation: 
  - &id "Department of Medical Statistics and Bioinformatics, Section Moleculair Epidemiology, Leiden University Medical Center,
  Leiden, The Netherlands"  
  email: mviterson@gmail.com
- name: "Davy Cats"
  affiliation: *id  
  email: davycats.dc@gmail.com
- name: "Paul Hop"
  affiliation: *id    
  email: pjhop@gmail.com  
- name: "Bas T. Heijmans"
  affiliation: *id    
  email: b.t.heijmans@lumc.nl
date: "`r Sys.Date()`"
abstract: >
  The Aanalysis of multiple omics datatypes from the same
  individuals is becoming increasingly common. For example,
  several data repositories contain genetic, transcriptomic
  and epigenetic (DNA methylation) measurements on the same
  individuals, e.g., TCGA, Geuvadis, BBMRI/BIOS, etc. However,
  errors in the data linkage are almost inevitable in such
  complex projects (e.g. due to sample mix-ups) and unknown
  family relationships may be present. If not corrected, such
  errors may introduce false positive or false negative
  findings. To streamline necessary quality control, we have
  developed a tool to reliably verify the sample relationships
  between and across omics data types using genotype data that
  is directly measured or inferred from for example RNA-seq or
  DNA methylation array data.    	  
output: 
  BiocStyle::html_document:
    toc: true
    toc_float:
      collapsed: false
vignette: >
  %\VignetteIndexEntry{omicsPrint: detection of data linkage errors in multiple omics studies}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
bibliography: omicsPrint.bib
---

```{r setup, include=FALSE}	
suppressPackageStartupMessages({
    library(BiocStyle)
    library(omicsPrint)
    library(GEOquery)
    library(SummarizedExperiment)
})
```
	

```{r, downloaddata}	
library(GEOquery)
library(SummarizedExperiment)
##gset <- getGEO("GSE73412", GSEMatrix=TRUE, AnnotGPL=FALSE)
##this is more stable somehow?
file <- tempfile()
download.file("ftp://ftp.ncbi.nlm.nih.gov/geo/series/GSE73nnn/GSE73412/matrix/GSE73412_series_matrix.txt.gz", file)
gset <- getGEO(filename=file)

se <- makeSummarizedExperimentFromExpressionSet(gset)
se
```
	
```{r, extractrelations}	
library(omicsPrint)
r <- expand.grid(idx=colnames(se), idy=colnames(se))
r$Xfam <- substr(as.character(colData(se)[r$idx, "characteristics_ch1.3"]),
                 21, 29)
r$Yfam <- substr(as.character(colData(se)[r$idy, "characteristics_ch1.3"]),
                 21, 29)
r$Xrole <- substr(as.character(colData(se)[r$idx, "characteristics_ch1.3"]),
                  31, 50)
r$Yrole <- substr(as.character(colData(se)[r$idy, "characteristics_ch1.3"]),
                  31, 50)
r[r == " N/A"] <- ""

r$relationship <- "unrelated"

fun <- function(x) {
    if (x["idx"] == x["idy"]){
        return("identical")
    }

    if (x["Xfam"] == "" || x["Yfam"] == ""){
        return("unrelated")
    }
    ##print(x)
    if (x["Yfam"] == x["Xfam"]){
        roles <- x[c("Xrole", "Yrole")]
        ##print(roles)
        if ("(son)" %in% roles && "(father)" %in% roles){
            return("father/son")
        } else if ("(son)" %in% roles && "(grandfather)" %in% roles) {
            return("grandfather/grandson")
        } else if ("(son)" %in% roles && "(uncle)" %in% roles){
            return("uncle/nephew")
        } else if ("(father)" %in% roles && "(grandfather)" %in% roles) {
            return("father/son")
        } else if ("(father)" %in% roles && "(uncle)" %in% roles) {
            return("brother")
        } else if ("(grandfather)" %in% roles && "(uncle)" %in% roles) {
            return("father/son")
        } else if (sum(roles == "(uncle)") == 2 || sum(roles == "(son)") == 2) {
            return("brother")
        }
    } else {
        return("unrelated")
    }
}

r$relationship <- apply(r, 1, fun)
head(r)
```

```{r, omicsprint}	
data(hm450.manifest.pop.GoNL)
cpgs <- names(hm450.manifest.pop.GoNL[
    mcols(hm450.manifest.pop.GoNL)$MASK.snp5.EAS])

se2 <- se[cpgs,]

se3 <- se[, se$characteristics_ch1.3 != "family relationship: N/A"]
se4 <- se3[cpgs,]

gt <- beta2genotype(se4, assayName = "exprs")
data <- alleleSharing(gt, relations = r, rel.col = "relationship", verbose = TRUE)
mismatches <- inferRelations(data)
mismatches
```

# SessionInfo #

```{r, sessioninfo}
sessionInfo()
```


