RSCRIPT=Rscript

all:
#	${RSCRIPT} -e "rmarkdown::render('GSE102177_DNAm_siblings.Rmd', output_format = BiocStyle::html_document())"
#	${RSCRIPT} -e "rmarkdown::render('GSE52980_DNAm_tissues.Rmd', output_format = BiocStyle::html_document())"
#	${RSCRIPT} -e "rmarkdown::render('GSE73412_DNAm_familymen.Rmd', output_format = BiocStyle::html_document())"
	${RSCRIPT} -e "rmarkdown::render('GSE39672_DNAm_DNA.Rmd', output_format = BiocStyle::html_document())"
##	${RSCRIPT} -e "rmarkdown::render('GSE100227_DNAm_sisters.Rmd', output_format = BiocStyle::html_document())"
##	${RSCRIPT} -e "rmarkdown::render('omicsPrint.Rmd', output_format = BiocStyle::html_document())"







